name: reusable-deploy

on:
  workflow_call:
    inputs:
      connector_version: # fex: 8.5.7 - 8.5 for Camunda release, 7 for connector version
        required: true
        type: string
      cf_api_endpoint:
        required: true
        type: string
      cf_org:
        required: true
        type: string
      cf_space:
        required: true
        type: string

jobs:
  mtad-yaml: # get the mtad.yaml.example from the release branch via sparse checkout
    runs-on: ubuntu-latest
    steps:
      - name: extract release branch # first two digits of connector_version
        run: echo "camunda_release=$(echo ${{ inputs.connector_version }} | cut -d'.' -f1-2)" >> $GITHUB_ENV

      - name: checkout mtad.yaml.example
        uses: actions/checkout@v4
        with:
          repository: camunda/sap-rfc-connector
#          ref: release/${{ env.camunda_release }}
          path: yaml
          sparse-checkout: |
            mtad.yaml.example
          sparse-checkout-cone-mode: false

      - name: check
        run: |
          ls -al .
          ls -al yaml

      - name: fill in target cluster credentials
        run: |
          # replace dots in the connector_version with underscores
          mangledVersion=$(echo ${{ inputs.connector_version }} | tr '.' '_')
          cd yaml
          sed -i.bak -e "s/<app-version>/${{ inputs.connector_version }}/g" \
          -e "s/<mangled-version>/${mangledVersion}/g" \
          -e "s/name: sap-rfc-connector$/name: sap-rfc-connector-${{ inputs.connector_version }}/g" \
          -e "s/<your-cluster-id>/${{ secrets.C87_CLUSTER_ID }}/g" \
          -e "s/<client-id-credential-from-api-client>/${{ secrets.C87_CLIENT_ID }}/g" \
          -e "s/<client-secret-credential-from-api-client>/${{ secrets.C87_CLIENT_SECRET }}/g" \
          -e "s/<your-cluster-region>/${{ secrets.C87_REGION }}/g" \
          mtad.yaml.example
          mv mtad.yaml.example mtad.yaml
          cd ..

      # no worries: gh marks secrets with *** also when cat'ing files
      - name: check substitution result
        run: |
          ls -al yaml/mtad.yaml
          cat yaml/mtad.yaml

      - name: Upload mtad.yaml
        uses: actions/upload-artifact@v4
        with:
          name: mtad
          path: yaml/mtad.yaml

  deploy:
    needs: mtad-yaml
    runs-on: ubuntu-latest

    steps:
      - name: install cf cli
        run: |
          # sudo apt-get update
          sudo apt-get install -y wget
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          # wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo gpg --dearmor -o /usr/share/keyrings/cli.cloudfoundry.org.gpg
          # echo "deb [signed-by=/usr/share/keyrings/cli.cloudfoundry.org.gpg] https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install -y cf8-cli
          cf install-plugin multiapps -f

      # first, build the connector
      - uses: actions/checkout@v4

      - name: set up jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: build
        run: mvn package -DskipTests # as we've run the tests in the previous job

      # second, prep deployment descriptor
      - name: download mtad.yaml
        uses: actions/download-artifact@v4
        with:
          name: mtad

      # third, actual deployment
      - name: deploy ${{inputs.connector_version}} to BTP
        # download-artifact puts the file w/o subdir here
        run: |
          ls -al .
          cf login -a ${{ inputs.cf_api_endpoint }} -u ${{ secrets.CF_USER }} -p ${{ secrets.CF_PASSWORD }} -o ${{ inputs.cf_org }} -s ${{ inputs.cf_space }}
          cf deploy ./ -f
