name: reusable-build-and-test

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      distribution:
        required: true
        type: string
      maven-options:
        required: true
        type: string
      spring_profile:
        type: string

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up jdk ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.distribution }}
          cache: maven

      - name: install the jco library
        run: mvn install:install-file -Dfile=sapjco3.jar -DgroupId=com.sap.conn.jco -DartifactId=com.sap.conn.jco.sapjco3 -Dversion=3.1.10 -Dpackaging=jar

      - name: build and test with maven
        run: mvn ${{ inputs.maven-options }} test